name: thumbnail_youtube
description: A new Flutter project.

publish_to: "none"

version: 1.1.10+21

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter

    personal_dropdown:
        git:
            url: https://github.com/youmtinetflutterpacks/flutter-personal-dropdown.git
            ref: v1.0.7
    gallery_saver:
        git:
            url: https://github.com/youmtinetflutterpacks/gallery_saver.git
            ref: v4
    animated_theme_switcher: ^2.0.10
    shared_preferences: ^2.2.3
    firebase_messaging: ^14.7.10
    cupertino_icons: ^1.0.8
    cloud_firestore: ^4.14.0
    saver_gallery: ^3.0.3
    firebase_core: ^2.24.2
    path_provider: ^2.1.3
    provider: ^6.1.2
    http: ^1.1.0
    get: ^4.6.6
    intl: ^0.19.0
    gap: ^3.0.1
    path: ^1.8.3
    google_mobile_ads: ^4.0.0
    wakelock_plus: ^1.1.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.3.7

flutter_launcher_icons:
    image_path: src/design/launcher.png
    android: ic_launcher
    ios: true
    remove_alpha_ios: true
    adaptive_icon_background: "#FFFFFFFF"
    adaptive_icon_foreground: src/design/launcher.png

flutter:
    uses-material-design: true
    assets:
        - assets/
        - shorebird.yaml
