name: thumbnail_youtube
description: A new Flutter project.

publish_to: "none"

version: 1.1.10+21

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    shared_preferences: ^2.5.4
    cupertino_icons: ^1.0.8
    cloud_firestore: ^6.1.2
    saver_gallery: ^4.1.0
    firebase_core: ^4.4.0
    path_provider: ^2.1.5
    provider: ^6.1.5+1
    http: ^1.6.0
    get: ^4.7.3
    intl: ^0.20.2
    gap: ^3.0.1
    path: ^1.9.1
    google_mobile_ads: ^7.0.0
    # wakelock_plus: ^1.4.0
    url_launcher: ^6.3.1

    personal_dropdown:
        git:
            url: https://github.com/youmtinetflutterpacks/flutter-personal-dropdown.git
            ref: v1.0.7
    # gallery_saver:
    #     git:
    #         url: https://github.com/youmtinetflutterpacks/gallery_saver.git
    #         ref: v4
    google_fonts: ^8.0.1
    flutter_screenutil: ^5.9.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.3.7

flutter_launcher_icons:
    image_path: src/design/launcher.png
    android: ic_launcher
    ios: true
    remove_alpha_ios: true
    adaptive_icon_background: "#FFFFFFFF"
    adaptive_icon_foreground: src/design/launcher.png

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/
        - shorebird.yaml
